#!/bin/bash
# Based on https://developers.strava.com/docs/#client-code
# Generates a client in ./strava-client/.

set -e
set -o nounset

IMAGE=openapitools/openapi-generator-cli:v7.2.0

echo '===> Generate bindings'
rm -rf strava-client || true
docker run --rm \
  -v "${PWD}:/local" \
  ${IMAGE} \
    generate \
    -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
    -i https://developers.strava.com/swagger/swagger.json \
    -g rust \
    -o /local/strava-client \
    --additional-properties=supportMultipleResponses=true,useSingleRequestParameter=true,packageName=strava_client \
    --skip-validate-spec
